### ISSUE TITLE
AlphaBar minimum position

### ISSUE THREAD

**Issue by vikasWri** [rtugeek/ColorSeekBar#14]
Hi, this is awesome library for color seekbar. i am using library in my project. every thing is working awesome but i am stuck on a point. the point is can we set alpha bar minimum position. i don't want to allow user to set alpha bar position below 70. Is there any way to set alphabar minimum thumb position to 70.

Thanks in advance

**Comment by rtugeek** [comment]
This may help you a lot:
```
        mColorSeekBar.setOnColorChangeListener(new ColorSeekBar.OnColorChangeListener() {
            @Override
            public void onColorChangeListener(int colorBarPosition, int alphaBarPosition, int color) {
                if(alphaBarPosition < 70){
                    mColorSeekBar.setAlphaBarPosition(70);
                }
            }
        });
```

**Comment by vikasWri** [comment]
Nope, I have already....tried this but this is not working in my case....

**Comment by vikasWri** [comment]
can we set the initial value of alpha bar of your color seek bar. if it is possible that we can change the range of alpha seek bar from 70 to 255 then this will solve my problem.

What your solution does is it stops the thumb icon at 70 and user won't be able to drag the seekbar below 70 but what i am seeking is that seekbar's range itself should start from 70.

**Comment by rtugeek** [comment]
Please try the new version:
```
  compile 'com.github.rtugeek:ColorSeekBar:1.4.3'
```
And use:
```
mColorSeekBar.setAlphaMaxPosition(250);
mColorSeekBar.setAlphaMinPosition(70);
```

**Comment by vikasWri** [comment]
Thanks.....a lot
