### ISSUE TITLE
setColorSeeds(int[] colors) not working?

### ISSUE THREAD

**Issue by DarioNevistic** [rtugeek/ColorSeekBar#18]
In version 1.0.2 i used to set seekbar color by setColors(int[] colors), but in version 1.4.3 setColorSeeds() not working anymore.. It change just thumb color of seek bar.
Any reason for that?

**Comment by rtugeek** [comment]
Please show me your color seeds array, or code snippet

**Comment by DarioNevistic** [comment]
```
private void setColorSeekBar() {
        //getting current color from color picker and setting slider to that color
        colArray[0] = ColorUtils.setAlphaComponent(mCurrentColor, 0);
        colArray[1] = mCurrentColor;
        mSeekSlider.setColorSeeds(colArray);
    }
```

**Comment by rtugeek** [comment]
Please try the new version 1.5.2
If you got the 'Unable to merge dex' error, try to clean up your project

**Comment by DarioNevistic** [comment]
It's working now, thanks.

**Comment by NamorIT** [comment]
I have the same or similar issue using version 1.7.3.
I use an array with the codes of 6 main colours (red, yellow, green, cyan, blue, magenta).
ColorSeekBar is working properly, picks all the intermediate colours, but the bar is not displayed on the screen. I see only the thumb moving right and left, and the alphabar, both correctly changing their colours.
Tested on virtual device Android 6.0 and on Samsung Galaxy Note 4 Android 6.0.1

In build.gradle (app)
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}

dependencies {
  ...........
  compile 'com.github.rtugeek:colorseekbar:1.7.3'
}
```

in activity_main.xml
```
<com.rtugeek.android.colorseekbar.ColorSeekBar
  android:id="@+id/colorSlider"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:layout_marginTop="36dp"
  app:colorSeeds="@array/material_colors"
  app:layout_constraintEnd_toEndOf="parent"
  app:layout_constraintTop_toBottomOf="@+id/Yellow" />

```

In MainActivity java:
```
import com.rtugeek.android.colorseekbar.ColorSeekBar;
.........
ColorSeekBar colorSeekBar;
int[] colorArray = {16711680, 16776960, 65280, 65535, 255, 16711935};
colorSeekBar.setMaxPosition(151);
colorSeekBar.setColorSeeds(colorArray); 
colorSeekBar.setColorBarPosition(0); 
colorSeekBar.setAlphaBarPosition(0); 
colorSeekBar.setShowAlphaBar(true);
colorSeekBar.setBarHeight(14); 
colorSeekBar.setThumbHeight(30); 
colorSeekBar.setBarMargin(8);

```

**Comment by rtugeek** [comment]
@NamorIT It seems you use decimal integer color, this cause transparent ColorSeekBar. Please use [Color ints(0xAARRGGBB)](https://developer.android.com/reference/android/graphics/Color#color-ints) instead. 

For example, blue: 255(D) -> FF(H) ->0x000000FF(Color ints), By default ,the alpha value is 0, so it's transparent.  to avoid transparency, use 0xFF0000FF instead

**Comment by NamorIT** [comment]
You are definitely right.
I worried about the color codes and I did not think at all about the alpha channel.
It works perfectly now, thank you very much.
I tried out two ways for initialize the array, both working:

`int[] colorArray = {0xFFFF0000, 0xFFFFFF00,0xFF00FF00,0xFF00FFFF,0xFF0000FF,0xFFFF00FF};`
```
int[] colorArray = {
    argb(255,255,0,0),
    argb(255,255,255,0),
    argb(255,0,255,0),
    argb(255,0,255,255),
    argb(255,0,0,255),
    argb(255,255,0,255)};
```
Bye.
