### ISSUE TITLE
How to customize thumb ?

### ISSUE THREAD

**Issue by madhurihr1592** [rtugeek/ColorSeekBar#19]
How can I change the Thumb style in Color seekbar ? I want a circle kind of thumb.

**Comment by rtugeek** [comment]
[  draw color bar thumb](https://github.com/rtugeek/ColorSeekBar/blob/7edf71821da8fa9f2da05723ede70898a663cde5/colorseekbar/src/main/java/com/rtugeek/android/colorseekbar/ColorSeekBar.java#L250)
```
Paint thumbGradientPaint = new Paint();
thumbGradientPaint.setAntiAlias(true);
thumbGradientPaint.setColor(color);
thumbGradientPaint.setAlpha(50);
canvas.drawCircle(thumbX, thumbY, mThumbHeight / 2, thumbGradientPaint);
```
[ draw alpha bar thumb ](https://github.com/rtugeek/ColorSeekBar/blob/7edf71821da8fa9f2da05723ede70898a663cde5/colorseekbar/src/main/java/com/rtugeek/android/colorseekbar/ColorSeekBar.java#L275)
```
Paint alphaThumbGradientPaint = new Paint();
alphaThumbGradientPaint.setColor(color);
alphaThumbGradientPaint.setAlpha(50);
alphaThumbGradientPaint.setAntiAlias(true);
canvas.drawCircle(alphaThumbX, alphaThumbY, mThumbHeight / 2, alphaThumbGradientPaint);
```
