### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [rtugeek/ColorSeekBar#22]
Greetings @rtugeek  Sir, I am a graphic designer and an open source contributor. I would like to contribute to your good project by designing a logo for it which will add more visibility and interest from the users. I will be doing it for free as my gift to your project. If you permit me i will start immediately and show you my output here. Thanks and best regards!

-Tobaloidee

**Comment by rtugeek** [comment]
That's welcomed! @Tobaloidee

**Comment by Tobaloidee** [comment]
Hello @rtugeek  here's my logo design for your nice project:

CONCEPT- i based the design from the circular point on the seekbar. I put 2 bars based from the demo illustration. it is neat and alive and also has the elements that was inspired from the actual appearance of the seekbar.

![pres-01-01-01](https://user-images.githubusercontent.com/36028424/41811984-6fd08596-774c-11e8-842a-e9aa16c2e384.png)

I hope you'll like it, Still open for your suggestions if you have any. Thanks!

**Comment by rtugeek** [comment]
Hello, @Tobaloidee  
Cool illustrations! I really appreciate your graphic design skill, Thank you very much.
And there is a suggestion here:
This one with a transparent background will be better
![screenshot from 2018-06-25 11-51-03](https://user-images.githubusercontent.com/6168238/41829568-1305cbd2-786e-11e8-8b2e-80adef4c319c.png)

Once you finish your logo, just fork this project, put the logo inside the readme.md file and make a pull request.
Or you can send the logo.png to me, I will make the update by myself.

Thank you for your logos and nice job.

**Comment by Tobaloidee** [comment]
Yes Sir! Im glad you liked it..i will upload the png and svg file of it and create a PR..

**Comment by Tobaloidee** [comment]
Here's the PR #23 Sir, Thanks! -Tobaloidee
