### ISSUE TITLE
Vertical Seekbar

### ISSUE THREAD

**Issue by NehaParmar** [rtugeek/ColorSeekBar#3]
Can we make this color Seekbar vertical? 
How if yes

**Comment by rtugeek** [comment]
For my release version is exactly not support this feature , It's a good idea ,I will make it support after some time ,because I am busy for working now .Or you can fix this feature by yourself ,fork + pull request and I will greatly appreciate it!

**Comment by DLTech21** [comment]
有时间弄成垂直的吗

**Comment by rtugeek** [comment]
Try this beta version 1.3.1  
compile 'com.github.rtugeek:ColorSeekBar:1.3.1'
