### ISSUE TITLE
Disable Thumb

### ISSUE THREAD

**Issue by ravikiran18** [rtugeek/ColorSeekBar#30]
Can we completely make the thumb disappear?

**Comment by rtugeek** [comment]
This feature doesn't support yet. Can you show me your usage case that I can make this feature better

**Comment by ravikiran18** [comment]
I wanna implement the colour picker which is similar to that of whats app. Since your picker is in the same way I want to make the thumb disappear.

**Comment by rtugeek** [comment]
Please try 1.7.4
