### ISSUE TITLE
Custom slider

### ISSUE THREAD

**Issue by GXSZone** [rtugeek/ColorSeekBar#34]
Add a method to customize the slider setDrawable(int drawable) and setDrawable(Drawable drawable)

**Comment by GXSZone** [comment]
The transparent selection bar adds a background image such as Photoshop to indicate transparency

![Screenshot_2021-05-21-00-05-07-86](https://user-images.githubusercontent.com/12530096/119012061-465c8b80-b9c8-11eb-8679-cfd367ebf1ea.jpg)

**Comment by rtugeek** [comment]
Please try 2.0.0

**Comment by GXSZone** [comment]
thinks
