### ISSUE TITLE
Add option to change ColorBar color on new colorSeeds

### ISSUE THREAD

**Issue by EddieXu123** [rtugeek/ColorSeekBar#35]
Hi there! I was trying to build an app with two ColorSeekBars - one to control the hue of my view and one to control the saturation. When I change my hue colorSeekBar, the colorSeeds of my saturation colorSeekBar change to (Color.WHITE, hueSeekBar.getColor()). This works well, but when I try dragging the saturationSeekBar, the color of the thumb remains unchanged (the original value). How would I go about doing this? Thank you!

![App](https://user-images.githubusercontent.com/50087436/162245355-d154a3f6-4d3d-4ada-834d-f384909c6e8d.png)

**Comment by EddieXu123** [comment]
Ahh nevermind, I found a tutorial a minute after sending this Issue: https://www.geeksforgeeks.org/how-to-add-colorseekbar-in-android/



Great stuff btw!


PS. I tried adding the stuff from the tutorial and it works, but I was wondering if you could include the showAlphaBar option back in the latest version?

**Comment by rtugeek** [comment]
@EddieXu123 showAlphaBar was removed in version 2.0.*, please use **AlphaSeekbar** to control the alpha channel value,  use **alphaSeekBar.setOnAlphaChangeListener** to watch value changed.  

```XML
<com.rtugeek.android.colorseekbar.AlphaSeekBar 
    android:id="@+id/alphaSeekBar"
    android:layout_width="match_parent" 
    android:layout_height="wrap_content" />
```

If you want to merge AlphaSeekBar's alpha into ColorSeekBar's color, use this:
```java
int color = colorSeekBar.getColor()
int alpha = alphaSeekBar.getAlphaValue()
Color.argb(alpha, Color.red(color), Color.green(color), Color.blue(color))
```
```kotlin
/**
 * if you use Kotlin, this extension function may help
 * mix alpha value  (0-255) into current color
 */
fun Int.mixAlpha(@IntRange(from = 0, to = 255) alpha: Int): Int {
    return Color.argb(alpha, Color.red(this), Color.green(this), Color.blue(this))
}
```

**Comment by EddieXu123** [comment]
Thank you! I was also wondering, for now the .getColor() of the bar seems to return an integer in the negatives. I was just wondering how you would transfer this number to hsv? Or if not hsv RGB? Thanks!

**Comment by rtugeek** [comment]
```kotlin
val hsv = FloatArray(3)
Color.colorToHSV(colorInt,hsv)
//hsv[0] is Hue \([0..360[\)
//hsv[1] is Saturation \([0...1]\)
//hsv[2] is Value \([0...1]\)

// hsv to color int
Color.HSVToColor(hsv)
```

**Comment by EddieXu123** [comment]
Thank you! Sorry, I'm really new to Android development so I just had one last question: If I want to add another seekbar to change the brightness of my view (using a ColorMatrixColorFilter), I was wondering how to go about that? This is what I'm doing so far:
```
public ColorMatrixColorFilter brightIt(int fb) {
        ColorMatrix cmB = new ColorMatrix();
        cmB.set(new float[] {
                1, 0, 0, 0, fb,
                0, 1, 0, 0, fb,
                0, 0, 1, 0, fb,
                0, 0, 0, 1, 0   });

        ColorMatrix colorMatrix = new ColorMatrix();
        colorMatrix.set(cmB);
        
        ColorMatrixColorFilter f = new ColorMatrixColorFilter(colorMatrix);
        return f;
    }
```

And then when changing the brightness slider:

```
brightness_seekbar.setOnColorChangeListener((colorBarPosition, alphaBarPosition, color) -> {
         float[] hsv = new float[3];
         Color.colorToHSV(color,hsv);
         imView.setColorFilter(brightIt(hsv[2]));
        
});
```

(Assuming the code is correct -> I did some reformatting, just trying to figure out how to get my ImageView to remain the same saturation_seekbar color while changing the brightness using that ColorMatrix). Thank you so much for all your help!

**Comment by rtugeek** [comment]
https://stackoverflow.com/a/9226771/4639921
This answer may help you.  Use PorterDuffColorFilter instead of ColorMatrixColorFilter

**Comment by EddieXu123** [comment]
Got it, thank you so much! It works now after using a GradientDrawable and that helper function :)
