### ISSUE TITLE
Set thumb at particular color

### ISSUE THREAD

**Issue by NikolaDespotoski** [rtugeek/ColorSeekBar#6]
I have a color (rgb) and I need to set the thumb at that color?

I have tried to loop over until I find the thumb at that color, like:

```
mRgbSeekbar.setMaxValue(100);
 private void findSeekBarRgb(int rgb) {
            int current = 0;
            while(current <= 100){
                mRgbSeekBar.setColorBarValue(current);
                int color = mRgbSeekBar.getColor();
                if(rgb == color) return;
                current++;
            }
        }
```

Is there any convenient method?

**Comment by rtugeek** [comment]
Nope.  I think this method should be supported. I will do it  :-)

**Comment by rtugeek** [comment]
#10 
Sorry it's too later, But I still hope you can enjoy using it 😃
